version: "3"

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - TZ=Europe/Budapest
    volumes:
      - "./docker/mysql/var/lib/mysql:/var/lib/mysql:rw"
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY:-1}
      - PMA_HOST=db
      # - PMA_PORT=3306 
      # - PMA_USER=root
      # - PMA_PASSWORD=password
    ports:
      - "${PORT_PHPMYADMIN:-8882}:80"
    networks:
      - database


networks: 
  database:
    driver: bridge