version: "3"

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --sql-mode="ANSI_QUOTES"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - TZ="${TZ:-Europe/Budapest}"
    ports:
      - "${PORT_DATABSE:-33061}:3306"
    volumes:
      - "./docker/mysql/var/lib/mysql:/var/lib/mysql:rw"
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin:5.1-apache
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY:-0}
      - PMA_HOST=${PMA_HOST:-db}
      - PMA_PORT=${PMA_PORT:-3306} 
      # - PMA_USER=${PMA_USER:-root}
      # - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "${PORT_PHPMYADMIN:-8882}:80"
    volumes:
      - ./docker/phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - database


networks: 
  database:
    driver: bridge
