services:
  db:
    image: mysql:8.0.38
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}"
    ports:
      - ${PORT_DATABSE}:3306
    volumes:
      - dbdata:/var/lib/mysql:rw
    networks:
      - database

  phpmyadmin:
    image: rcsnjszg/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT} 
    ports:
      - ${PORT_PHPMYADMIN}:80
    networks:
      - database

volumes:
  dbdata:

networks: 
  database:
